(function () {
  "use strict";

  const I18N = {
    zh: {
      title: "射擊遊戲",
      subtitle: "固定式第一人稱射擊訓練",
      start: "開始",
      testWall: "測槍牆",
      settings: "設定",
      records: "成績",
      language: "語言",
      back: "返回",
      retry: "重試",
      menu: "主選單",
      continue: "繼續",
      directStart: "直接開始",
      tutorial: "關卡教學",
      setup: "任務設定",
      customize: "改槍",
      save: "儲存",
      reset: "重設",
      formal: "正式",
      custom: "自訂",
      level: "關卡",
      difficulty: "難度",
      weapon: "武器",
      config: "配置",
      standardWeapon: "標準槍",
      customConfig: "自訂配置",
      slot: "槽位",
      pause: "暫停",
      result: "結算",
      passed: "通過",
      failed: "失敗",
      ammo: "彈藥",
      reserve: "備彈",
      objective: "目標",
      time: "時間",
      accuracy: "命中率",
      weakRate: "弱點率",
      ammoEfficiency: "彈藥效率",
      avgReaction: "平均反應",
      rating: "評等",
      noRecords: "還沒有成績。",
      gyroscope: "陀螺儀",
      gyroOn: "陀螺儀已啟用：傾斜手機瞄準",
      gyroOff: "陀螺儀未啟用",
      gyroCalibrating: "保持目前姿勢，陀螺儀正在校準。",
      gyroReady: "陀螺儀已校準",
      gyroUnsupported: "此裝置或瀏覽器不支援陀螺儀。",
      reload: "換彈",
      aim: "開鏡",
      shoot: "射擊",
      controlsHint: "點擊畫面鎖定滑鼠焦點；準星固定中央。移動滑鼠瞄準，左鍵射擊，右鍵開鏡，R 換彈，Esc 暫停。",
      mobileHint: "橫向遊玩。拖曳空白區瞄準，使用觸控按鈕射擊、開鏡與換彈。",
      rotateTitle: "請將手機轉為橫向",
      rotateBody: "射擊遊戲需要橫向畫面以保留瞄準與按鈕空間。",
      failureAmmo: "彈藥耗盡，目標尚未清除。",
      failureBreach: "防線被突破。",
      failureQuit: "任務中止。",
      expertImpact: "專家彈道：橘色點為預期落點",
      emptyClick: "空槍",
      reloading: "換彈中",
      saved: "已儲存",
      resetDone: "已重設",
      bindingHint: "按下一個鍵來設定",
      lockMouseTitle: "點擊畫面鎖定滑鼠",
      lockMouseBody: "桌面模式需要鎖定滑鼠焦點，鎖定後滑鼠與中央準星會保持一致。",
    },
    en: {
      title: "Shooting Game",
      subtitle: "Fixed-position FPS training",
      start: "Start",
      testWall: "Test Wall",
      settings: "Settings",
      records: "Records",
      language: "Language",
      back: "Back",
      retry: "Retry",
      menu: "Main Menu",
      continue: "Continue",
      directStart: "Start Now",
      tutorial: "Tutorial",
      setup: "Mission Setup",
      customize: "Customize",
      save: "Save",
      reset: "Reset",
      formal: "Formal",
      custom: "Custom",
      level: "Level",
      difficulty: "Difficulty",
      weapon: "Weapon",
      config: "Config",
      standardWeapon: "Standard",
      customConfig: "Custom Config",
      slot: "Slot",
      pause: "Pause",
      result: "Results",
      passed: "Cleared",
      failed: "Failed",
      ammo: "Ammo",
      reserve: "Reserve",
      objective: "Objective",
      time: "Time",
      accuracy: "Accuracy",
      weakRate: "Weakpoint",
      ammoEfficiency: "Ammo Efficiency",
      avgReaction: "Avg Reaction",
      rating: "Rating",
      noRecords: "No records yet.",
      gyroscope: "Gyro",
      gyroOn: "Gyro enabled: tilt to aim",
      gyroOff: "Gyro disabled",
      gyroCalibrating: "Hold this position while gyro calibrates.",
      gyroReady: "Gyro calibrated",
      gyroUnsupported: "Gyroscope is not supported by this device or browser.",
      reload: "Reload",
      aim: "ADS",
      shoot: "Shoot",
      controlsHint: "Click the play area to lock mouse focus. The crosshair stays centered. Move mouse to aim, left click shoots, right click ADS, R reloads, Esc pauses.",
      mobileHint: "Play in landscape. Drag empty screen to aim and use touch buttons for actions.",
      rotateTitle: "Rotate Your Phone",
      rotateBody: "This game needs landscape space for aiming and controls.",
      failureAmmo: "Ammo exhausted before objectives were cleared.",
      failureBreach: "The defense line was breached.",
      failureQuit: "Mission aborted.",
      expertImpact: "Expert ballistics: orange dot shows expected impact",
      emptyClick: "Empty",
      reloading: "Reloading",
      saved: "Saved",
      resetDone: "Reset complete",
      bindingHint: "Press a key to bind",
      lockMouseTitle: "Click To Lock Mouse",
      lockMouseBody: "Desktop play requires mouse lock so the pointer focus matches the centered crosshair.",
    },
  };

  const LEVELS = {
    range: {
      id: "range",
      order: 1,
      name: { zh: "室內靶場", en: "Indoor Range" },
      short: { zh: "靶場", en: "Range" },
      objective: 10,
      description: {
        zh: "隨機出現的紙靶與鋼靶。清除 10 個目標，考驗反應、準度與彈藥管理。",
        en: "Random paper and steel targets. Clear 10 targets with good reaction, accuracy, and ammo discipline.",
      },
      tutorial: {
        zh: "準星點到目標中心即可命中。弱點通常在靶心，彈藥有限，換彈時不能射擊。",
        en: "Place the crosshair on the target to hit. Weakpoints are usually centered. Ammo is finite and you cannot shoot while reloading.",
      },
    },
    defense: {
      id: "defense",
      order: 2,
      name: { zh: "防守走廊", en: "Defense Corridor" },
      short: { zh: "防守", en: "Defense" },
      objective: 15,
      description: {
        zh: "訓練敵人會左右橫移並逐步靠近。阻止 15 個目標突破防線。",
        en: "Training enemies strafe while advancing. Stop 15 targets before they breach the line.",
      },
      tutorial: {
        zh: "敵人越近越大也越危險。優先處理距離最近的目標，必要時提早換彈。",
        en: "Closer enemies are larger and more dangerous. Prioritize near targets and reload early when needed.",
      },
    },
    sniper: {
      id: "sniper",
      order: 3,
      name: { zh: "戶外狙擊場", en: "Outdoor Sniper Range" },
      short: { zh: "狙擊", en: "Sniper" },
      objective: 5,
      description: {
        zh: "5 個遠距目標混合靜止、移動與短暫出現。專家難度會啟用風偏與下墜。",
        en: "Five distant targets mix stationary, moving, and brief exposure patterns. Expert difficulty enables drift and drop.",
      },
      tutorial: {
        zh: "遠距目標很小，開鏡能提高穩定度。專家難度請看橘色預期落點來補償彈道。",
        en: "Distant targets are small. ADS improves stability. In Expert, use the orange impact marker to compensate.",
      },
    },
  };

  const DIFFICULTIES = {
    newbie: {
      id: "newbie",
      name: { zh: "新兵", en: "Newbie" },
      targetSpeed: 0.76,
      spawnPace: 0.85,
      advance: 0.72,
      ammo: 1.2,
      ratingBias: 0.92,
      description: { zh: "較慢、彈藥較寬裕。", en: "Slower targets and more forgiving ammo." },
    },
    standard: {
      id: "standard",
      name: { zh: "標準", en: "Standard" },
      targetSpeed: 1,
      spawnPace: 1,
      advance: 1,
      ammo: 1,
      ratingBias: 1,
      description: { zh: "平衡訓練標準。", en: "Balanced training baseline." },
    },
    expert: {
      id: "expert",
      name: { zh: "專家", en: "Expert" },
      targetSpeed: 1.28,
      spawnPace: 1.16,
      advance: 1.28,
      ammo: 0.86,
      ratingBias: 1.08,
      description: { zh: "速度更快，第三關啟用風偏與下墜。", en: "Faster targets. Level 3 uses drift and drop." },
    },
  };

  const WEAPONS = {
    pistol: {
      id: "pistol",
      name: { zh: "手槍", en: "Pistol" },
      role: { zh: "穩定、低火力", en: "Stable, low power" },
      damage: 1,
      magSize: 10,
      reserve: 40,
      fireRate: 3.2,
      reloadMs: 1050,
      adsMs: 150,
      recoil: 10,
      spread: 7,
      sway: 3.2,
      recovery: 8.8,
      zoom: 1.15,
      stability: 84,
    },
    rifle: {
      id: "rifle",
      name: { zh: "步槍", en: "Rifle" },
      role: { zh: "均衡、適合防守", en: "Balanced, defensive" },
      damage: 1.25,
      magSize: 24,
      reserve: 72,
      fireRate: 7.2,
      reloadMs: 1550,
      adsMs: 220,
      recoil: 15,
      spread: 9,
      sway: 4.5,
      recovery: 7.4,
      zoom: 1.35,
      stability: 70,
    },
    sniper: {
      id: "sniper",
      name: { zh: "狙擊槍", en: "Sniper Rifle" },
      role: { zh: "高傷害、高倍率、慢", en: "High power, high zoom, slow" },
      damage: 3.2,
      magSize: 5,
      reserve: 20,
      fireRate: 0.95,
      reloadMs: 2300,
      adsMs: 430,
      recoil: 31,
      spread: 5,
      sway: 7.8,
      recovery: 5.1,
      zoom: 2.4,
      stability: 62,
    },
  };

  const ATTACHMENTS = {
    optic: [
      {
        id: "iron",
        name: { zh: "機械瞄具", en: "Iron Sights" },
        mods: { zoom: 0.95, adsMs: 0.86, sway: 0.95 },
        scope: "iron",
      },
      {
        id: "redDot",
        name: { zh: "紅點鏡", en: "Red Dot" },
        mods: { zoom: 1.12, adsMs: 0.95, spread: 0.92 },
        scope: "dot",
      },
      {
        id: "lowPower",
        name: { zh: "低倍鏡", en: "Low-Power Optic" },
        mods: { zoom: 1.45, adsMs: 1.08, sway: 1.04, spread: 0.88 },
        scope: "low",
      },
      {
        id: "highPower",
        name: { zh: "高倍狙擊鏡", en: "High-Power Scope" },
        mods: { zoom: 2.1, adsMs: 1.28, sway: 1.16, spread: 0.82 },
        scope: "scope",
      },
    ],
    muzzle: [
      { id: "standard", name: { zh: "標準槍口", en: "Standard Muzzle" }, mods: {} },
      { id: "brake", name: { zh: "制退器", en: "Muzzle Brake" }, mods: { recoil: 0.82, spread: 1.08 } },
      { id: "comp", name: { zh: "補償器", en: "Compensator" }, mods: { recoil: 0.9, recovery: 1.12 } },
      { id: "suppressor", name: { zh: "抑制器", en: "Suppressor" }, mods: { recoil: 0.94, damage: 0.92, adsMs: 1.04 } },
    ],
    grip: [
      { id: "none", name: { zh: "無握把", en: "No Grip" }, mods: {} },
      { id: "vertical", name: { zh: "垂直握把", en: "Vertical Grip" }, mods: { recoil: 0.86, adsMs: 1.07 } },
      { id: "angled", name: { zh: "斜角握把", en: "Angled Grip" }, mods: { adsMs: 0.9, recovery: 1.08 } },
      { id: "precision", name: { zh: "精準握把", en: "Precision Grip" }, mods: { spread: 0.84, sway: 0.9, fireRate: 0.96 } },
    ],
    magazine: [
      { id: "standard", name: { zh: "標準彈匣", en: "Standard Magazine" }, mods: {} },
      { id: "extended", name: { zh: "加長彈匣", en: "Extended Magazine" }, mods: { magSize: 1.45, reloadMs: 1.16, adsMs: 1.04 } },
      { id: "quick", name: { zh: "快速彈匣", en: "Quick Magazine" }, mods: { reloadMs: 0.82, magSize: 0.9 } },
      { id: "drum", name: { zh: "鼓式彈匣", en: "Drum Magazine" }, mods: { magSize: 2.2, reloadMs: 1.36, adsMs: 1.16, sway: 1.12 } },
    ],
    stock: [
      { id: "standard", name: { zh: "標準槍托", en: "Standard Stock" }, mods: {} },
      { id: "heavy", name: { zh: "重型槍托", en: "Heavy Stock" }, mods: { recoil: 0.82, sway: 0.92, adsMs: 1.12 } },
      { id: "light", name: { zh: "輕量槍托", en: "Light Stock" }, mods: { adsMs: 0.9, recoil: 1.1 } },
      { id: "marksman", name: { zh: "射手槍托", en: "Marksman Stock" }, mods: { spread: 0.86, recovery: 1.1, fireRate: 0.94 } },
    ],
    ammoType: [
      { id: "standard", name: { zh: "標準彈", en: "Standard Ammo" }, mods: {} },
      { id: "match", name: { zh: "競賽彈", en: "Match Ammo" }, mods: { damage: 1.04, spread: 0.82, reserve: 0.82 } },
      { id: "light", name: { zh: "輕量彈", en: "Light Ammo" }, mods: { recoil: 0.88, damage: 0.86, fireRate: 1.05 } },
      { id: "heavy", name: { zh: "重彈頭", en: "Heavy Rounds" }, mods: { damage: 1.22, recoil: 1.18, fireRate: 0.9 } },
    ],
  };

  const SLIDERS = [
    { id: "damage", name: { zh: "傷害", en: "Damage" }, min: 30, max: 300, step: 5, neutral: 100, higherBetter: true },
    { id: "recoil", name: { zh: "後座力", en: "Recoil" }, min: 10, max: 260, step: 5, neutral: 100, higherBetter: false },
    { id: "spread", name: { zh: "散布", en: "Spread" }, min: 10, max: 260, step: 5, neutral: 100, higherBetter: false },
    { id: "magSize", name: { zh: "彈匣", en: "Magazine" }, min: 40, max: 320, step: 5, neutral: 100, higherBetter: true },
    { id: "reserve", name: { zh: "備彈", en: "Reserve" }, min: 30, max: 300, step: 5, neutral: 100, higherBetter: true },
    { id: "fireRate", name: { zh: "射速", en: "Fire Rate" }, min: 35, max: 260, step: 5, neutral: 100, higherBetter: true },
    { id: "reloadMs", name: { zh: "換彈時間", en: "Reload Time" }, min: 35, max: 220, step: 5, neutral: 100, higherBetter: false },
    { id: "adsMs", name: { zh: "開鏡速度", en: "ADS Speed" }, min: 35, max: 220, step: 5, neutral: 100, higherBetter: false },
    { id: "zoom", name: { zh: "倍率", en: "Zoom" }, min: 50, max: 260, step: 5, neutral: 100, higherBetter: true },
    { id: "sway", name: { zh: "呼吸晃動", en: "Breath Sway" }, min: 10, max: 260, step: 5, neutral: 100, higherBetter: false },
  ];

  const DEFAULT_BINDINGS = {
    reload: "KeyR",
    pause: "Escape",
  };

  const DEFAULT_TOUCH_LAYOUT = {
    shoot: { x: 86, y: 72 },
    ads: { x: 74, y: 50 },
    reload: { x: 18, y: 72 },
    gyro: { x: 18, y: 50 },
    pause: { x: 93, y: 14 },
  };

  const DEFAULT_SETTINGS = {
    language: "zh",
    masterVolume: 0.75,
    sfxVolume: 0.8,
    musicVolume: 0.35,
    mouseSensitivity: 1,
    touchSensitivity: 1,
    gyroSensitivity: 0.8,
    invertY: false,
    touchSize: 70,
    touchOpacity: 0.64,
    crosshair: "cross",
    screenShake: 0.65,
    quality: "standard",
    bindings: DEFAULT_BINDINGS,
    touchLayout: DEFAULT_TOUCH_LAYOUT,
  };

  window.GameData = {
    I18N,
    LEVELS,
    DIFFICULTIES,
    WEAPONS,
    ATTACHMENTS,
    SLIDERS,
    DEFAULT_BINDINGS,
    DEFAULT_TOUCH_LAYOUT,
    DEFAULT_SETTINGS,
  };
})();
